### ISSUE TITLE
List/GiveItem command not working

### ISSUE THREAD

**Issue by DinoNuggets2** [Exiled-Team/CustomItems#86] opened 2022-04-12 22:29 UTC
**Describe the bug**
Remote Admin list and giveitem commands not working

**To Reproduce**
1. Go to Remote Admin
2. Attempt to give yourself an existing item, or "ci l r"

**Expected behavior**
Expecting the GiveCommand to give you the item, and the List Registered command to list all existing itemsp

**Server logs**
[Please include a pastebin of your localadmin log file (or both MA_log and SCP_log files if you use MultiAdmin) from the time in which the bug occured](https://pastebin.com/JR8p0W2t)

**EXILED Version ("latest" is not a version):**
EXILED 5.1.1

**Results of `show plugins` command in console:**
                                 Enabled plugins: 27
                                 Disabled plugins: 7
                                 
                                 Exiled.Events:
                                        - Author: Exiled Team
                                        - Version: 5.1.1.0
                                        - Required Exiled Version: 5.1.1.0
                                        - Prefix: exiled_events
                                        - Priority: Highest
                                 CedMod:
                                        - Author: ced777ric#8321
                                        - Version: 3.1.1
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: cm
                                        - Priority: Highest
                                 Spectator Shooting Range:
                                        - Author: rayzer
                                        - Version: 2.0.0
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: spectator_shooting_range
                                        - Priority: Higher
                                 NukeLock:
                                        - Author: Marco15453
                                        - Version: 1.9.0
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: nuke_lock
                                        - Priority: Medium
                                 SummonRespawnVehicles:
                                        - Author: 
                                        - Version: 1.0.0.0
                                        - Required Exiled Version: 5.1.1.0
                                        - Prefix: summon_respawn_vehicles
                                        - Priority: Medium
                                 AnnoyngPopUps:
                                        - Disabled
                                        - Author: Exiled Team
                                        - Version: 1.0.5
                                        - Required Exiled Version: 4.2.2
                                        - Prefix: annoyng_pop_ups
                                        - Priority: Medium
                                 CustomItems:
                                        - Author: Exiled Team
                                        - Version: 6.0.2.0
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: custom_items
                                        - Priority: Medium
                                 Exiled.CreditTags:
                                        - Author: Babyboucher20 & iRebbok & Exiled Team
                                        - Version: 5.1.1.0
                                        - Required Exiled Version: 5.1.1.0
                                        - Prefix: exiled_credits
                                        - Priority: Medium
                                 Battery:
                                        - Author: ErrorSaid
                                        - Version: 1.0.0.0
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: RadioBattery
                                        - Priority: Medium
                                 Exiled.Updater:
                                        - Disabled
                                        - Author: Exiled.Updater
                                        - Version: 3.1.1.0
                                        - Required Exiled Version: 5.1.1.0
                                        - Prefix: exiled_updater
                                        - Priority: Medium
                                 SCP-575:
                                        - Disabled
                                        - Author: Joker119
                                        - Version: 4.0.0
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: 575
                                        - Priority: Medium
                                 UIURescueSquad:
                                        - Author: JesusQC, Michal78900, maintained by Marco15453
                                        - Version: 3.2.0
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: UIURescueSquad
                                        - Priority: Medium
                                 WaitAndChillReborn:
                                        - Author: Michal78900
                                        - Version: 5.0.0
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: wait_and_chill_reborn
                                        - Priority: Medium
                                 Common Utilities:
                                        - Author: Galaxy119
                                        - Version: 6.0.0.0
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: CommonUtilities
                                        - Priority: Medium
                                 LightsRE:
                                        - Author: Beryl - (Contributors: BuildBoy12)
                                        - Version: 5.0.0
                                        - Required Exiled Version: 5.0.5
                                        - Prefix: lights
                                        - Priority: Medium
                                 Exiled.CustomItems:
                                        - Author: Exiled Team
                                        - Version: 5.1.1.0
                                        - Required Exiled Version: 5.1.1.0
                                        - Prefix: exiled_custom_items
                                        - Priority: Medium
                                 LogArchiver:
                                        - Author: Galaxy119
                                        - Version: 1.0.0
                                        - Required Exiled Version: 2.1.18
                                        - Prefix: LogArchiver
                                        - Priority: Medium
                                 Exiled.Permissions:
                                        - Author: Exiled Team
                                        - Version: 5.1.1.0
                                        - Required Exiled Version: 5.1.1.0
                                        - Prefix: exiled_permissions
                                        - Priority: Medium
                                 OmegaWarhead:
                                        - Author: ClaudioPanConQueso
                                        - Version: 1.0.0.0
                                        - Required Exiled Version: 5.1.1.0
                                        - Prefix: omega_warhead
                                        - Priority: Medium
                                 SCP1162:
                                        - Author: xRoier
                                        - Version: 4.0.0
                                        - Required Exiled Version: 4.0.0
                                        - Prefix: scp1162
                                        - Priority: Medium
                                 CustomDoorAccess:
                                        - Disabled
                                        - Author: Faety
                                        - Version: 1.4.0
                                        - Required Exiled Version: 3.7.2
                                        - Prefix: cda
                                        - Priority: Medium
                                 DiscordIntegration:
                                        - Author: Exiled Team
                                        - Version: 5.0.5.0
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: discord_integration
                                        - Priority: Medium
                                 Stalky106:
                                        - Author: RogerFK && Raul125
                                        - Version: 3.3.0
                                        - Required Exiled Version: 4.2.3
                                        - Prefix: ST106
                                        - Priority: Medium
                                 RespawnTimer:
                                        - Author: Michal78900
                                        - Version: 3.1.0
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: respawn_timer
                                        - Priority: Medium
                                 AnimatedServerTitle:
                                        - Disabled
                                        - Author: Killers0992
                                        - Version: 1.0.1
                                        - Required Exiled Version: 5.1.1.0
                                        - Prefix: animatedservertitle
                                        - Priority: Medium
                                 SupplyDrop:
                                        - Author: Wafel, KadeDev, JesusQC
                                        - Version: 3.3.0
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: SD
                                        - Priority: Medium
                                 KillMessage:
                                        - Author: GabiRP
                                        - Version: 1.0.5
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: kill_message
                                        - Priority: Medium
                                 MapEditorReborn:
                                        - Author: Michal78900 (original idea by Killers0992)
                                        - Version: 2.0.0
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: map_editor_reborn
                                        - Priority: Medium
                                 LeftHandedPlayers:
                                        - Author: TemmieGamerGuy
                                        - Version: 1.0.1
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: left_handed_players
                                        - Priority: Medium
                                 CustomWarheadColor:
                                        - Disabled
                                        - Author: SoraCént
                                        - Version: 0.3.0
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: custom_warhead_color
                                        - Priority: Medium
                                 Admin Tools:
                                        - Author: Originally by Galaxy119. Modifications by KoukoCocoa & Thomasjosif
                                        - Version: 5.0.0.0
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: AT
                                        - Priority: Medium
                                 Exiled.CustomRoles:
                                        - Author: Exiled Team
                                        - Version: 5.1.1.0
                                        - Required Exiled Version: 5.1.1.0
                                        - Prefix: exiled_custom_roles
                                        - Priority: Medium
                                 Scp035:
                                        - Disabled
                                        - Author: Joker119
                                        - Version: 4.0.3
                                        - Required Exiled Version: 5.0.0
                                        - Prefix: Scp035
                                        - Priority: Medium
                                 Smelly096:
                                        - Author: x3rt
                                        - Version: 1.0.0
                                        - Required Exiled Version: 3.0.0
                                        - Prefix: smelly096
                                        - Priority: Lowest

**Additional context**
![SCPSL 4_12_2022 6_15_17 PM](https://user-images.githubusercontent.com/91291118/163065461-f57b1f12-d4fb-467e-899a-3824ab719d9c.png)

**Comment by joker-119** [comment] 2022-04-12 23:02
Duplicate of #85

**Closed by joker-119** 2022-04-12 23:02 UTC
Labels: duplicate

**Comment by Hamster12012** [comment] 2022-04-12 23:48
![image](https://user-images.githubusercontent.com/94808550/163072465-7db8dca2-5b22-4ee9-92ff-378c7a05fc8f.png)
Got this error after latest relase

**Comment by joker-119** [comment] 2022-04-13 01:39
update the plugin again.

**Comment by Hamster12012** [comment] 2022-04-13 10:08
Everythign works as should be, thanks
